# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'his_uiLXuhhU.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPlainTextEdit,
    QSizePolicy, QStatusBar, QTabWidget, QWidget)

from player_case import PlayerCase
from player_trash import PlayerTrash

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        self.action_clear = QAction(MainWindow)
        self.action_clear.setObjectName(u"action_clear")
        self.action_report = QAction(MainWindow)
        self.action_report.setObjectName(u"action_report")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabs_object = QTabWidget(self.centralwidget)
        self.tabs_object.setObjectName(u"tabs_object")
        self.tabs_object.setGeometry(QRect(0, 0, 1281, 681))
        self.tabs_object.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.tabs_object.setTabPosition(QTabWidget.TabPosition.North)
        self.at_tab = QWidget()
        self.at_tab.setObjectName(u"at_tab")
        self.forward_case_trio1_lw = PlayerCase(self.at_tab)
        self.forward_case_trio1_lw.setObjectName(u"forward_case_trio1_lw")
        self.forward_case_trio1_lw.setGeometry(QRect(40, 40, 291, 61))
        self.forward_case_trio1_lw.setAutoFillBackground(False)
        self.forward_case_trio1_lw.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio1_lw.setFrameShadow(QFrame.Shadow.Sunken)
        self.image = QLabel(self.forward_case_trio1_lw)
        self.image.setObjectName(u"image")
        self.image.setGeometry(QRect(0, 0, 51, 61))
        self.image.setScaledContents(True)
        self.player_name = QLabel(self.forward_case_trio1_lw)
        self.player_name.setObjectName(u"player_name")
        self.player_name.setGeometry(QRect(60, 0, 231, 31))
        font = QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.player_name.setFont(font)
        self.season = QLabel(self.forward_case_trio1_lw)
        self.season.setObjectName(u"season")
        self.season.setGeometry(QRect(60, 20, 231, 31))
        font1 = QFont()
        font1.setPointSize(11)
        self.season.setFont(font1)
        self.forward_case_trio1_c = PlayerCase(self.at_tab)
        self.forward_case_trio1_c.setObjectName(u"forward_case_trio1_c")
        self.forward_case_trio1_c.setGeometry(QRect(390, 40, 291, 61))
        self.forward_case_trio1_c.setAutoFillBackground(False)
        self.forward_case_trio1_c.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio1_c.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_2 = QLabel(self.forward_case_trio1_c)
        self.image_2.setObjectName(u"image_2")
        self.image_2.setGeometry(QRect(0, 0, 51, 61))
        self.image_2.setScaledContents(True)
        self.player_name_2 = QLabel(self.forward_case_trio1_c)
        self.player_name_2.setObjectName(u"player_name_2")
        self.player_name_2.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_2.setFont(font)
        self.season_2 = QLabel(self.forward_case_trio1_c)
        self.season_2.setObjectName(u"season_2")
        self.season_2.setGeometry(QRect(60, 20, 231, 31))
        self.season_2.setFont(font1)
        self.forward_case_trio1_rw = PlayerCase(self.at_tab)
        self.forward_case_trio1_rw.setObjectName(u"forward_case_trio1_rw")
        self.forward_case_trio1_rw.setGeometry(QRect(740, 40, 291, 61))
        self.forward_case_trio1_rw.setAutoFillBackground(False)
        self.forward_case_trio1_rw.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio1_rw.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_3 = QLabel(self.forward_case_trio1_rw)
        self.image_3.setObjectName(u"image_3")
        self.image_3.setGeometry(QRect(0, 0, 51, 61))
        self.image_3.setScaledContents(True)
        self.player_name_3 = QLabel(self.forward_case_trio1_rw)
        self.player_name_3.setObjectName(u"player_name_3")
        self.player_name_3.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_3.setFont(font)
        self.season_3 = QLabel(self.forward_case_trio1_rw)
        self.season_3.setObjectName(u"season_3")
        self.season_3.setGeometry(QRect(60, 20, 231, 31))
        self.season_3.setFont(font1)
        self.forward_case_trio2_lw = PlayerCase(self.at_tab)
        self.forward_case_trio2_lw.setObjectName(u"forward_case_trio2_lw")
        self.forward_case_trio2_lw.setGeometry(QRect(40, 170, 291, 61))
        self.forward_case_trio2_lw.setAutoFillBackground(False)
        self.forward_case_trio2_lw.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio2_lw.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_4 = QLabel(self.forward_case_trio2_lw)
        self.image_4.setObjectName(u"image_4")
        self.image_4.setGeometry(QRect(0, 0, 51, 61))
        self.image_4.setScaledContents(True)
        self.player_name_4 = QLabel(self.forward_case_trio2_lw)
        self.player_name_4.setObjectName(u"player_name_4")
        self.player_name_4.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_4.setFont(font)
        self.season_4 = QLabel(self.forward_case_trio2_lw)
        self.season_4.setObjectName(u"season_4")
        self.season_4.setGeometry(QRect(60, 20, 231, 31))
        self.season_4.setFont(font1)
        self.forward_case_trio2_c = PlayerCase(self.at_tab)
        self.forward_case_trio2_c.setObjectName(u"forward_case_trio2_c")
        self.forward_case_trio2_c.setGeometry(QRect(390, 170, 291, 61))
        self.forward_case_trio2_c.setAutoFillBackground(False)
        self.forward_case_trio2_c.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio2_c.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_5 = QLabel(self.forward_case_trio2_c)
        self.image_5.setObjectName(u"image_5")
        self.image_5.setGeometry(QRect(0, 0, 51, 61))
        self.image_5.setScaledContents(True)
        self.player_name_5 = QLabel(self.forward_case_trio2_c)
        self.player_name_5.setObjectName(u"player_name_5")
        self.player_name_5.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_5.setFont(font)
        self.season_5 = QLabel(self.forward_case_trio2_c)
        self.season_5.setObjectName(u"season_5")
        self.season_5.setGeometry(QRect(60, 20, 231, 31))
        self.season_5.setFont(font1)
        self.forward_case_trio2_rw = PlayerCase(self.at_tab)
        self.forward_case_trio2_rw.setObjectName(u"forward_case_trio2_rw")
        self.forward_case_trio2_rw.setGeometry(QRect(740, 170, 291, 61))
        self.forward_case_trio2_rw.setAutoFillBackground(False)
        self.forward_case_trio2_rw.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio2_rw.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_6 = QLabel(self.forward_case_trio2_rw)
        self.image_6.setObjectName(u"image_6")
        self.image_6.setGeometry(QRect(0, 0, 51, 61))
        self.image_6.setScaledContents(True)
        self.player_name_6 = QLabel(self.forward_case_trio2_rw)
        self.player_name_6.setObjectName(u"player_name_6")
        self.player_name_6.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_6.setFont(font)
        self.season_6 = QLabel(self.forward_case_trio2_rw)
        self.season_6.setObjectName(u"season_6")
        self.season_6.setGeometry(QRect(60, 20, 231, 31))
        self.season_6.setFont(font1)
        self.forward_case_trio3_lw = PlayerCase(self.at_tab)
        self.forward_case_trio3_lw.setObjectName(u"forward_case_trio3_lw")
        self.forward_case_trio3_lw.setGeometry(QRect(40, 300, 291, 61))
        self.forward_case_trio3_lw.setAutoFillBackground(False)
        self.forward_case_trio3_lw.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio3_lw.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_7 = QLabel(self.forward_case_trio3_lw)
        self.image_7.setObjectName(u"image_7")
        self.image_7.setGeometry(QRect(0, 0, 51, 61))
        self.image_7.setScaledContents(True)
        self.player_name_7 = QLabel(self.forward_case_trio3_lw)
        self.player_name_7.setObjectName(u"player_name_7")
        self.player_name_7.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_7.setFont(font)
        self.season_7 = QLabel(self.forward_case_trio3_lw)
        self.season_7.setObjectName(u"season_7")
        self.season_7.setGeometry(QRect(60, 20, 231, 31))
        self.season_7.setFont(font1)
        self.forward_case_trio3_c = PlayerCase(self.at_tab)
        self.forward_case_trio3_c.setObjectName(u"forward_case_trio3_c")
        self.forward_case_trio3_c.setGeometry(QRect(390, 300, 291, 61))
        self.forward_case_trio3_c.setAutoFillBackground(False)
        self.forward_case_trio3_c.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio3_c.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_8 = QLabel(self.forward_case_trio3_c)
        self.image_8.setObjectName(u"image_8")
        self.image_8.setGeometry(QRect(0, 0, 51, 61))
        self.image_8.setScaledContents(True)
        self.player_name_8 = QLabel(self.forward_case_trio3_c)
        self.player_name_8.setObjectName(u"player_name_8")
        self.player_name_8.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_8.setFont(font)
        self.season_8 = QLabel(self.forward_case_trio3_c)
        self.season_8.setObjectName(u"season_8")
        self.season_8.setGeometry(QRect(60, 20, 231, 31))
        self.season_8.setFont(font1)
        self.forward_case_trio3_rw = PlayerCase(self.at_tab)
        self.forward_case_trio3_rw.setObjectName(u"forward_case_trio3_rw")
        self.forward_case_trio3_rw.setGeometry(QRect(740, 300, 291, 61))
        self.forward_case_trio3_rw.setAutoFillBackground(False)
        self.forward_case_trio3_rw.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio3_rw.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_9 = QLabel(self.forward_case_trio3_rw)
        self.image_9.setObjectName(u"image_9")
        self.image_9.setGeometry(QRect(0, 0, 51, 61))
        self.image_9.setScaledContents(True)
        self.player_name_9 = QLabel(self.forward_case_trio3_rw)
        self.player_name_9.setObjectName(u"player_name_9")
        self.player_name_9.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_9.setFont(font)
        self.season_9 = QLabel(self.forward_case_trio3_rw)
        self.season_9.setObjectName(u"season_9")
        self.season_9.setGeometry(QRect(60, 20, 231, 31))
        self.season_9.setFont(font1)
        self.forward_case_trio4_lw = PlayerCase(self.at_tab)
        self.forward_case_trio4_lw.setObjectName(u"forward_case_trio4_lw")
        self.forward_case_trio4_lw.setGeometry(QRect(40, 430, 291, 61))
        self.forward_case_trio4_lw.setAutoFillBackground(False)
        self.forward_case_trio4_lw.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio4_lw.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_10 = QLabel(self.forward_case_trio4_lw)
        self.image_10.setObjectName(u"image_10")
        self.image_10.setGeometry(QRect(0, 0, 51, 61))
        self.image_10.setScaledContents(True)
        self.player_name_10 = QLabel(self.forward_case_trio4_lw)
        self.player_name_10.setObjectName(u"player_name_10")
        self.player_name_10.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_10.setFont(font)
        self.season_10 = QLabel(self.forward_case_trio4_lw)
        self.season_10.setObjectName(u"season_10")
        self.season_10.setGeometry(QRect(60, 20, 231, 31))
        self.season_10.setFont(font1)
        self.forward_case_trio4_c = PlayerCase(self.at_tab)
        self.forward_case_trio4_c.setObjectName(u"forward_case_trio4_c")
        self.forward_case_trio4_c.setGeometry(QRect(390, 430, 291, 61))
        self.forward_case_trio4_c.setAutoFillBackground(False)
        self.forward_case_trio4_c.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio4_c.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_11 = QLabel(self.forward_case_trio4_c)
        self.image_11.setObjectName(u"image_11")
        self.image_11.setGeometry(QRect(0, 0, 51, 61))
        self.image_11.setScaledContents(True)
        self.player_name_11 = QLabel(self.forward_case_trio4_c)
        self.player_name_11.setObjectName(u"player_name_11")
        self.player_name_11.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_11.setFont(font)
        self.season_11 = QLabel(self.forward_case_trio4_c)
        self.season_11.setObjectName(u"season_11")
        self.season_11.setGeometry(QRect(60, 20, 231, 31))
        self.season_11.setFont(font1)
        self.forward_case_trio4_rw = PlayerCase(self.at_tab)
        self.forward_case_trio4_rw.setObjectName(u"forward_case_trio4_rw")
        self.forward_case_trio4_rw.setGeometry(QRect(740, 430, 291, 61))
        self.forward_case_trio4_rw.setAutoFillBackground(False)
        self.forward_case_trio4_rw.setFrameShape(QFrame.Shape.StyledPanel)
        self.forward_case_trio4_rw.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_12 = QLabel(self.forward_case_trio4_rw)
        self.image_12.setObjectName(u"image_12")
        self.image_12.setGeometry(QRect(0, 0, 51, 61))
        self.image_12.setScaledContents(True)
        self.player_name_12 = QLabel(self.forward_case_trio4_rw)
        self.player_name_12.setObjectName(u"player_name_12")
        self.player_name_12.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_12.setFont(font)
        self.season_12 = QLabel(self.forward_case_trio4_rw)
        self.season_12.setObjectName(u"season_12")
        self.season_12.setGeometry(QRect(60, 20, 231, 31))
        self.season_12.setFont(font1)
        self.trio1_name_input = QLineEdit(self.at_tab)
        self.trio1_name_input.setObjectName(u"trio1_name_input")
        self.trio1_name_input.setGeometry(QRect(40, 10, 991, 26))
        self.trio2_name_input = QLineEdit(self.at_tab)
        self.trio2_name_input.setObjectName(u"trio2_name_input")
        self.trio2_name_input.setGeometry(QRect(40, 140, 991, 26))
        self.trio3_name_input = QLineEdit(self.at_tab)
        self.trio3_name_input.setObjectName(u"trio3_name_input")
        self.trio3_name_input.setGeometry(QRect(40, 270, 991, 26))
        self.trio4_name_input = QLineEdit(self.at_tab)
        self.trio4_name_input.setObjectName(u"trio4_name_input")
        self.trio4_name_input.setGeometry(QRect(40, 400, 991, 26))
        self.player_trash_0 = PlayerTrash(self.at_tab)
        self.player_trash_0.setObjectName(u"player_trash_0")
        self.player_trash_0.setGeometry(QRect(1180, 550, 81, 80))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(237, 51, 59, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        brush2 = QBrush(QColor(255, 155, 160, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush2)
        brush3 = QBrush(QColor(246, 103, 109, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush3)
        brush4 = QBrush(QColor(118, 25, 29, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush4)
        brush5 = QBrush(QColor(158, 34, 39, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        brush7 = QBrush(QColor(246, 153, 157, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush7)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
        brush9 = QBrush(QColor(0, 0, 0, 127))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
        brush10 = QBrush(QColor(118, 25, 29, 127))
        brush10.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush10)
#endif
        brush11 = QBrush(QColor(255, 108, 114, 255))
        brush11.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush11)
#endif
        self.player_trash_0.setPalette(palette)
        self.player_trash_0.setCursor(QCursor(Qt.CursorShape.CrossCursor))
        self.player_trash_0.setFrameShape(QFrame.Shape.StyledPanel)
        self.player_trash_0.setFrameShadow(QFrame.Shadow.Raised)
        self.tabs_object.addTab(self.at_tab, "")
        self.dp_tab = QWidget()
        self.dp_tab.setObjectName(u"dp_tab")
        self.defender_case_pair1_ld = PlayerCase(self.dp_tab)
        self.defender_case_pair1_ld.setObjectName(u"defender_case_pair1_ld")
        self.defender_case_pair1_ld.setGeometry(QRect(40, 40, 291, 61))
        self.defender_case_pair1_ld.setAutoFillBackground(False)
        self.defender_case_pair1_ld.setFrameShape(QFrame.Shape.StyledPanel)
        self.defender_case_pair1_ld.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_13 = QLabel(self.defender_case_pair1_ld)
        self.image_13.setObjectName(u"image_13")
        self.image_13.setGeometry(QRect(0, 0, 51, 61))
        self.image_13.setScaledContents(True)
        self.player_name_13 = QLabel(self.defender_case_pair1_ld)
        self.player_name_13.setObjectName(u"player_name_13")
        self.player_name_13.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_13.setFont(font)
        self.season_13 = QLabel(self.defender_case_pair1_ld)
        self.season_13.setObjectName(u"season_13")
        self.season_13.setGeometry(QRect(60, 20, 231, 31))
        self.season_13.setFont(font1)
        self.defender_case_pair1_rd = PlayerCase(self.dp_tab)
        self.defender_case_pair1_rd.setObjectName(u"defender_case_pair1_rd")
        self.defender_case_pair1_rd.setGeometry(QRect(390, 40, 291, 61))
        self.defender_case_pair1_rd.setAutoFillBackground(False)
        self.defender_case_pair1_rd.setFrameShape(QFrame.Shape.StyledPanel)
        self.defender_case_pair1_rd.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_14 = QLabel(self.defender_case_pair1_rd)
        self.image_14.setObjectName(u"image_14")
        self.image_14.setGeometry(QRect(0, 0, 51, 61))
        self.image_14.setScaledContents(True)
        self.player_name_14 = QLabel(self.defender_case_pair1_rd)
        self.player_name_14.setObjectName(u"player_name_14")
        self.player_name_14.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_14.setFont(font)
        self.season_16 = QLabel(self.defender_case_pair1_rd)
        self.season_16.setObjectName(u"season_16")
        self.season_16.setGeometry(QRect(60, 20, 231, 31))
        self.season_16.setFont(font1)
        self.trio1_name_input_2 = QLineEdit(self.dp_tab)
        self.trio1_name_input_2.setObjectName(u"trio1_name_input_2")
        self.trio1_name_input_2.setGeometry(QRect(40, 10, 641, 26))
        self.defender_case_pair2_ld = PlayerCase(self.dp_tab)
        self.defender_case_pair2_ld.setObjectName(u"defender_case_pair2_ld")
        self.defender_case_pair2_ld.setGeometry(QRect(40, 170, 291, 61))
        self.defender_case_pair2_ld.setAutoFillBackground(False)
        self.defender_case_pair2_ld.setFrameShape(QFrame.Shape.StyledPanel)
        self.defender_case_pair2_ld.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_16 = QLabel(self.defender_case_pair2_ld)
        self.image_16.setObjectName(u"image_16")
        self.image_16.setGeometry(QRect(0, 0, 51, 61))
        self.image_16.setScaledContents(True)
        self.player_name_15 = QLabel(self.defender_case_pair2_ld)
        self.player_name_15.setObjectName(u"player_name_15")
        self.player_name_15.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_15.setFont(font)
        self.season_14 = QLabel(self.defender_case_pair2_ld)
        self.season_14.setObjectName(u"season_14")
        self.season_14.setGeometry(QRect(60, 20, 231, 31))
        self.season_14.setFont(font1)
        self.trio1_name_input_3 = QLineEdit(self.dp_tab)
        self.trio1_name_input_3.setObjectName(u"trio1_name_input_3")
        self.trio1_name_input_3.setGeometry(QRect(40, 140, 641, 26))
        self.defender_case_pair2_rd = PlayerCase(self.dp_tab)
        self.defender_case_pair2_rd.setObjectName(u"defender_case_pair2_rd")
        self.defender_case_pair2_rd.setGeometry(QRect(390, 170, 291, 61))
        self.defender_case_pair2_rd.setAutoFillBackground(False)
        self.defender_case_pair2_rd.setFrameShape(QFrame.Shape.StyledPanel)
        self.defender_case_pair2_rd.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_17 = QLabel(self.defender_case_pair2_rd)
        self.image_17.setObjectName(u"image_17")
        self.image_17.setGeometry(QRect(0, 0, 51, 61))
        self.image_17.setScaledContents(True)
        self.player_name_16 = QLabel(self.defender_case_pair2_rd)
        self.player_name_16.setObjectName(u"player_name_16")
        self.player_name_16.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_16.setFont(font)
        self.season_17 = QLabel(self.defender_case_pair2_rd)
        self.season_17.setObjectName(u"season_17")
        self.season_17.setGeometry(QRect(60, 20, 231, 31))
        self.season_17.setFont(font1)
        self.defender_case_pair3_ld = PlayerCase(self.dp_tab)
        self.defender_case_pair3_ld.setObjectName(u"defender_case_pair3_ld")
        self.defender_case_pair3_ld.setGeometry(QRect(40, 300, 291, 61))
        self.defender_case_pair3_ld.setAutoFillBackground(False)
        self.defender_case_pair3_ld.setFrameShape(QFrame.Shape.StyledPanel)
        self.defender_case_pair3_ld.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_19 = QLabel(self.defender_case_pair3_ld)
        self.image_19.setObjectName(u"image_19")
        self.image_19.setGeometry(QRect(0, 0, 51, 61))
        self.image_19.setScaledContents(True)
        self.player_name_17 = QLabel(self.defender_case_pair3_ld)
        self.player_name_17.setObjectName(u"player_name_17")
        self.player_name_17.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_17.setFont(font)
        self.season_15 = QLabel(self.defender_case_pair3_ld)
        self.season_15.setObjectName(u"season_15")
        self.season_15.setGeometry(QRect(60, 20, 231, 31))
        self.season_15.setFont(font1)
        self.trio1_name_input_4 = QLineEdit(self.dp_tab)
        self.trio1_name_input_4.setObjectName(u"trio1_name_input_4")
        self.trio1_name_input_4.setGeometry(QRect(40, 270, 641, 26))
        self.defender_case_pair3_rd = PlayerCase(self.dp_tab)
        self.defender_case_pair3_rd.setObjectName(u"defender_case_pair3_rd")
        self.defender_case_pair3_rd.setGeometry(QRect(390, 300, 291, 61))
        self.defender_case_pair3_rd.setAutoFillBackground(False)
        self.defender_case_pair3_rd.setFrameShape(QFrame.Shape.StyledPanel)
        self.defender_case_pair3_rd.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_20 = QLabel(self.defender_case_pair3_rd)
        self.image_20.setObjectName(u"image_20")
        self.image_20.setGeometry(QRect(0, 0, 51, 61))
        self.image_20.setScaledContents(True)
        self.player_name_18 = QLabel(self.defender_case_pair3_rd)
        self.player_name_18.setObjectName(u"player_name_18")
        self.player_name_18.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_18.setFont(font)
        self.season_18 = QLabel(self.defender_case_pair3_rd)
        self.season_18.setObjectName(u"season_18")
        self.season_18.setGeometry(QRect(60, 20, 231, 31))
        self.season_18.setFont(font1)
        self.label = QLabel(self.dp_tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(950, 20, 291, 18))
        self.goalkeeper_case_backup = PlayerCase(self.dp_tab)
        self.goalkeeper_case_backup.setObjectName(u"goalkeeper_case_backup")
        self.goalkeeper_case_backup.setGeometry(QRect(950, 170, 291, 61))
        self.goalkeeper_case_backup.setAutoFillBackground(False)
        self.goalkeeper_case_backup.setFrameShape(QFrame.Shape.StyledPanel)
        self.goalkeeper_case_backup.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_18 = QLabel(self.goalkeeper_case_backup)
        self.image_18.setObjectName(u"image_18")
        self.image_18.setGeometry(QRect(0, 0, 51, 61))
        self.image_18.setScaledContents(True)
        self.player_name_20 = QLabel(self.goalkeeper_case_backup)
        self.player_name_20.setObjectName(u"player_name_20")
        self.player_name_20.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_20.setFont(font)
        self.season_20 = QLabel(self.goalkeeper_case_backup)
        self.season_20.setObjectName(u"season_20")
        self.season_20.setGeometry(QRect(60, 20, 231, 31))
        self.season_20.setFont(font1)
        self.label_2 = QLabel(self.dp_tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(950, 150, 291, 18))
        self.goalkeeper_case_starter = PlayerCase(self.dp_tab)
        self.goalkeeper_case_starter.setObjectName(u"goalkeeper_case_starter")
        self.goalkeeper_case_starter.setGeometry(QRect(950, 40, 291, 61))
        self.goalkeeper_case_starter.setAutoFillBackground(False)
        self.goalkeeper_case_starter.setFrameShape(QFrame.Shape.StyledPanel)
        self.goalkeeper_case_starter.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_15 = QLabel(self.goalkeeper_case_starter)
        self.image_15.setObjectName(u"image_15")
        self.image_15.setGeometry(QRect(0, 0, 51, 61))
        self.image_15.setScaledContents(True)
        self.player_name_19 = QLabel(self.goalkeeper_case_starter)
        self.player_name_19.setObjectName(u"player_name_19")
        self.player_name_19.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_19.setFont(font)
        self.season_19 = QLabel(self.goalkeeper_case_starter)
        self.season_19.setObjectName(u"season_19")
        self.season_19.setGeometry(QRect(60, 20, 231, 31))
        self.season_19.setFont(font1)
        self.player_trash_1 = PlayerTrash(self.dp_tab)
        self.player_trash_1.setObjectName(u"player_trash_1")
        self.player_trash_1.setGeometry(QRect(1180, 550, 81, 80))
        palette1 = QPalette()
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush2)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush3)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush4)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush5)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush6)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush7)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush8)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush2)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush3)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush4)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush5)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush6)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush7)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush8)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush4)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush2)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush3)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush4)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush5)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush4)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush6)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush4)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush8)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush10)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush11)
#endif
        self.player_trash_1.setPalette(palette1)
        self.player_trash_1.setCursor(QCursor(Qt.CursorShape.CrossCursor))
        self.player_trash_1.setFrameShape(QFrame.Shape.StyledPanel)
        self.player_trash_1.setFrameShadow(QFrame.Shadow.Raised)
        self.tabs_object.addTab(self.dp_tab, "")
        self.r_tab = QWidget()
        self.r_tab.setObjectName(u"r_tab")
        self.reserve_case_lw_1 = PlayerCase(self.r_tab)
        self.reserve_case_lw_1.setObjectName(u"reserve_case_lw_1")
        self.reserve_case_lw_1.setGeometry(QRect(40, 40, 291, 61))
        self.reserve_case_lw_1.setAutoFillBackground(False)
        self.reserve_case_lw_1.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_lw_1.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_21 = QLabel(self.reserve_case_lw_1)
        self.image_21.setObjectName(u"image_21")
        self.image_21.setGeometry(QRect(0, 0, 51, 61))
        self.image_21.setScaledContents(True)
        self.player_name_21 = QLabel(self.reserve_case_lw_1)
        self.player_name_21.setObjectName(u"player_name_21")
        self.player_name_21.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_21.setFont(font)
        self.season_21 = QLabel(self.reserve_case_lw_1)
        self.season_21.setObjectName(u"season_21")
        self.season_21.setGeometry(QRect(60, 20, 231, 31))
        self.season_21.setFont(font1)
        self.label_3 = QLabel(self.r_tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 20, 291, 18))
        self.reserve_case_rw_1 = PlayerCase(self.r_tab)
        self.reserve_case_rw_1.setObjectName(u"reserve_case_rw_1")
        self.reserve_case_rw_1.setGeometry(QRect(360, 40, 291, 61))
        self.reserve_case_rw_1.setAutoFillBackground(False)
        self.reserve_case_rw_1.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_rw_1.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_22 = QLabel(self.reserve_case_rw_1)
        self.image_22.setObjectName(u"image_22")
        self.image_22.setGeometry(QRect(0, 0, 51, 61))
        self.image_22.setScaledContents(True)
        self.player_name_22 = QLabel(self.reserve_case_rw_1)
        self.player_name_22.setObjectName(u"player_name_22")
        self.player_name_22.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_22.setFont(font)
        self.season_22 = QLabel(self.reserve_case_rw_1)
        self.season_22.setObjectName(u"season_22")
        self.season_22.setGeometry(QRect(60, 20, 231, 31))
        self.season_22.setFont(font1)
        self.label_7 = QLabel(self.r_tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(360, 20, 291, 18))
        self.reserve_case_c_1 = PlayerCase(self.r_tab)
        self.reserve_case_c_1.setObjectName(u"reserve_case_c_1")
        self.reserve_case_c_1.setGeometry(QRect(680, 40, 291, 61))
        self.reserve_case_c_1.setAutoFillBackground(False)
        self.reserve_case_c_1.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_c_1.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_23 = QLabel(self.reserve_case_c_1)
        self.image_23.setObjectName(u"image_23")
        self.image_23.setGeometry(QRect(0, 0, 51, 61))
        self.image_23.setScaledContents(True)
        self.player_name_23 = QLabel(self.reserve_case_c_1)
        self.player_name_23.setObjectName(u"player_name_23")
        self.player_name_23.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_23.setFont(font)
        self.season_23 = QLabel(self.reserve_case_c_1)
        self.season_23.setObjectName(u"season_23")
        self.season_23.setGeometry(QRect(60, 20, 231, 31))
        self.season_23.setFont(font1)
        self.label_8 = QLabel(self.r_tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(680, 20, 291, 18))
        self.reserve_case_lw_2 = PlayerCase(self.r_tab)
        self.reserve_case_lw_2.setObjectName(u"reserve_case_lw_2")
        self.reserve_case_lw_2.setGeometry(QRect(40, 120, 291, 61))
        self.reserve_case_lw_2.setAutoFillBackground(False)
        self.reserve_case_lw_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_lw_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_24 = QLabel(self.reserve_case_lw_2)
        self.image_24.setObjectName(u"image_24")
        self.image_24.setGeometry(QRect(0, 0, 51, 61))
        self.image_24.setScaledContents(True)
        self.player_name_24 = QLabel(self.reserve_case_lw_2)
        self.player_name_24.setObjectName(u"player_name_24")
        self.player_name_24.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_24.setFont(font)
        self.season_24 = QLabel(self.reserve_case_lw_2)
        self.season_24.setObjectName(u"season_24")
        self.season_24.setGeometry(QRect(60, 20, 231, 31))
        self.season_24.setFont(font1)
        self.reserve_case_rw_2 = PlayerCase(self.r_tab)
        self.reserve_case_rw_2.setObjectName(u"reserve_case_rw_2")
        self.reserve_case_rw_2.setGeometry(QRect(360, 120, 291, 61))
        self.reserve_case_rw_2.setAutoFillBackground(False)
        self.reserve_case_rw_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_rw_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_25 = QLabel(self.reserve_case_rw_2)
        self.image_25.setObjectName(u"image_25")
        self.image_25.setGeometry(QRect(0, 0, 51, 61))
        self.image_25.setScaledContents(True)
        self.player_name_25 = QLabel(self.reserve_case_rw_2)
        self.player_name_25.setObjectName(u"player_name_25")
        self.player_name_25.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_25.setFont(font)
        self.season_25 = QLabel(self.reserve_case_rw_2)
        self.season_25.setObjectName(u"season_25")
        self.season_25.setGeometry(QRect(60, 20, 231, 31))
        self.season_25.setFont(font1)
        self.reserve_case_c_2 = PlayerCase(self.r_tab)
        self.reserve_case_c_2.setObjectName(u"reserve_case_c_2")
        self.reserve_case_c_2.setGeometry(QRect(680, 120, 291, 61))
        self.reserve_case_c_2.setAutoFillBackground(False)
        self.reserve_case_c_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_c_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_26 = QLabel(self.reserve_case_c_2)
        self.image_26.setObjectName(u"image_26")
        self.image_26.setGeometry(QRect(0, 0, 51, 61))
        self.image_26.setScaledContents(True)
        self.player_name_26 = QLabel(self.reserve_case_c_2)
        self.player_name_26.setObjectName(u"player_name_26")
        self.player_name_26.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_26.setFont(font)
        self.season_26 = QLabel(self.reserve_case_c_2)
        self.season_26.setObjectName(u"season_26")
        self.season_26.setGeometry(QRect(60, 20, 231, 31))
        self.season_26.setFont(font1)
        self.label_9 = QLabel(self.r_tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 210, 291, 18))
        self.reserve_case_ld_1 = PlayerCase(self.r_tab)
        self.reserve_case_ld_1.setObjectName(u"reserve_case_ld_1")
        self.reserve_case_ld_1.setGeometry(QRect(40, 230, 291, 61))
        self.reserve_case_ld_1.setAutoFillBackground(False)
        self.reserve_case_ld_1.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_ld_1.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_27 = QLabel(self.reserve_case_ld_1)
        self.image_27.setObjectName(u"image_27")
        self.image_27.setGeometry(QRect(0, 0, 51, 61))
        self.image_27.setScaledContents(True)
        self.player_name_27 = QLabel(self.reserve_case_ld_1)
        self.player_name_27.setObjectName(u"player_name_27")
        self.player_name_27.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_27.setFont(font)
        self.season_27 = QLabel(self.reserve_case_ld_1)
        self.season_27.setObjectName(u"season_27")
        self.season_27.setGeometry(QRect(60, 20, 231, 31))
        self.season_27.setFont(font1)
        self.reserve_case_ld_2 = PlayerCase(self.r_tab)
        self.reserve_case_ld_2.setObjectName(u"reserve_case_ld_2")
        self.reserve_case_ld_2.setGeometry(QRect(40, 310, 291, 61))
        self.reserve_case_ld_2.setAutoFillBackground(False)
        self.reserve_case_ld_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_ld_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_28 = QLabel(self.reserve_case_ld_2)
        self.image_28.setObjectName(u"image_28")
        self.image_28.setGeometry(QRect(0, 0, 51, 61))
        self.image_28.setScaledContents(True)
        self.player_name_28 = QLabel(self.reserve_case_ld_2)
        self.player_name_28.setObjectName(u"player_name_28")
        self.player_name_28.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_28.setFont(font)
        self.season_28 = QLabel(self.reserve_case_ld_2)
        self.season_28.setObjectName(u"season_28")
        self.season_28.setGeometry(QRect(60, 20, 231, 31))
        self.season_28.setFont(font1)
        self.reserve_case_rd_1 = PlayerCase(self.r_tab)
        self.reserve_case_rd_1.setObjectName(u"reserve_case_rd_1")
        self.reserve_case_rd_1.setGeometry(QRect(360, 230, 291, 61))
        self.reserve_case_rd_1.setAutoFillBackground(False)
        self.reserve_case_rd_1.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_rd_1.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_29 = QLabel(self.reserve_case_rd_1)
        self.image_29.setObjectName(u"image_29")
        self.image_29.setGeometry(QRect(0, 0, 51, 61))
        self.image_29.setScaledContents(True)
        self.player_name_29 = QLabel(self.reserve_case_rd_1)
        self.player_name_29.setObjectName(u"player_name_29")
        self.player_name_29.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_29.setFont(font)
        self.season_29 = QLabel(self.reserve_case_rd_1)
        self.season_29.setObjectName(u"season_29")
        self.season_29.setGeometry(QRect(60, 20, 231, 31))
        self.season_29.setFont(font1)
        self.label_10 = QLabel(self.r_tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(360, 210, 291, 18))
        self.reserve_case_rd_2 = PlayerCase(self.r_tab)
        self.reserve_case_rd_2.setObjectName(u"reserve_case_rd_2")
        self.reserve_case_rd_2.setGeometry(QRect(360, 310, 291, 61))
        self.reserve_case_rd_2.setAutoFillBackground(False)
        self.reserve_case_rd_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_rd_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_30 = QLabel(self.reserve_case_rd_2)
        self.image_30.setObjectName(u"image_30")
        self.image_30.setGeometry(QRect(0, 0, 51, 61))
        self.image_30.setScaledContents(True)
        self.player_name_30 = QLabel(self.reserve_case_rd_2)
        self.player_name_30.setObjectName(u"player_name_30")
        self.player_name_30.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_30.setFont(font)
        self.season_30 = QLabel(self.reserve_case_rd_2)
        self.season_30.setObjectName(u"season_30")
        self.season_30.setGeometry(QRect(60, 20, 231, 31))
        self.season_30.setFont(font1)
        self.reserve_case_g_1 = PlayerCase(self.r_tab)
        self.reserve_case_g_1.setObjectName(u"reserve_case_g_1")
        self.reserve_case_g_1.setGeometry(QRect(680, 230, 291, 61))
        self.reserve_case_g_1.setAutoFillBackground(False)
        self.reserve_case_g_1.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_g_1.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_31 = QLabel(self.reserve_case_g_1)
        self.image_31.setObjectName(u"image_31")
        self.image_31.setGeometry(QRect(0, 0, 51, 61))
        self.image_31.setScaledContents(True)
        self.player_name_31 = QLabel(self.reserve_case_g_1)
        self.player_name_31.setObjectName(u"player_name_31")
        self.player_name_31.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_31.setFont(font)
        self.season_31 = QLabel(self.reserve_case_g_1)
        self.season_31.setObjectName(u"season_31")
        self.season_31.setGeometry(QRect(60, 20, 231, 31))
        self.season_31.setFont(font1)
        self.label_11 = QLabel(self.r_tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(680, 210, 291, 18))
        self.reserve_case_g_2 = PlayerCase(self.r_tab)
        self.reserve_case_g_2.setObjectName(u"reserve_case_g_2")
        self.reserve_case_g_2.setGeometry(QRect(680, 310, 291, 61))
        self.reserve_case_g_2.setAutoFillBackground(False)
        self.reserve_case_g_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.reserve_case_g_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_32 = QLabel(self.reserve_case_g_2)
        self.image_32.setObjectName(u"image_32")
        self.image_32.setGeometry(QRect(0, 0, 51, 61))
        self.image_32.setScaledContents(True)
        self.player_name_32 = QLabel(self.reserve_case_g_2)
        self.player_name_32.setObjectName(u"player_name_32")
        self.player_name_32.setGeometry(QRect(60, 0, 231, 31))
        self.player_name_32.setFont(font)
        self.season_32 = QLabel(self.reserve_case_g_2)
        self.season_32.setObjectName(u"season_32")
        self.season_32.setGeometry(QRect(60, 20, 231, 31))
        self.season_32.setFont(font1)
        self.player_trash_2 = PlayerTrash(self.r_tab)
        self.player_trash_2.setObjectName(u"player_trash_2")
        self.player_trash_2.setGeometry(QRect(1180, 550, 81, 80))
        palette2 = QPalette()
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush2)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush3)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush4)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush5)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush6)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush7)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush8)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush2)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush3)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush4)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush5)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush6)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush7)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush8)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush4)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush2)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush3)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush4)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush5)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush4)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush6)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush4)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush8)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush10)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush11)
#endif
        self.player_trash_2.setPalette(palette2)
        self.player_trash_2.setCursor(QCursor(Qt.CursorShape.CrossCursor))
        self.player_trash_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.player_trash_2.setFrameShadow(QFrame.Shadow.Raised)
        self.tabs_object.addTab(self.r_tab, "")
        self.ap_tab = QWidget()
        self.ap_tab.setObjectName(u"ap_tab")
        self.chat_widget = QPlainTextEdit(self.ap_tab)
        self.chat_widget.setObjectName(u"chat_widget")
        self.chat_widget.setGeometry(QRect(0, 0, 1271, 591))
        font2 = QFont()
        font2.setFamilies([u"DejaVu Sans Condensed"])
        font2.setPointSize(12)
        self.chat_widget.setFont(font2)
        self.chat_widget.setReadOnly(True)
        self.message_input = QLineEdit(self.ap_tab)
        self.message_input.setObjectName(u"message_input")
        self.message_input.setGeometry(QRect(0, 590, 1271, 31))
        self.tabs_object.addTab(self.ap_tab, "")
        self.s_tab = QWidget()
        self.s_tab.setObjectName(u"s_tab")
        self.webEngineView = QWebEngineView(self.s_tab)
        self.webEngineView.setObjectName(u"webEngineView")
        self.webEngineView.setGeometry(QRect(0, 0, 1281, 641))
        self.webEngineView.setUrl(QUrl(u"https://www.hockey-reference.com/"))
        self.tabs_object.addTab(self.s_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 23))
        self.menu_functions = QMenu(self.menubar)
        self.menu_functions.setObjectName(u"menu_functions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_functions.menuAction())
        self.menu_functions.addAction(self.action_clear)
        self.menu_functions.addAction(self.action_report)

        self.retranslateUi(MainWindow)

        self.tabs_object.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_clear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.action_report.setText(QCoreApplication.translate("MainWindow", u"Report", None))
        self.image.setText("")
        self.player_name.setText("")
        self.season.setText("")
        self.image_2.setText("")
        self.player_name_2.setText("")
        self.season_2.setText("")
        self.image_3.setText("")
        self.player_name_3.setText("")
        self.season_3.setText("")
        self.image_4.setText("")
        self.player_name_4.setText("")
        self.season_4.setText("")
        self.image_5.setText("")
        self.player_name_5.setText("")
        self.season_5.setText("")
        self.image_6.setText("")
        self.player_name_6.setText("")
        self.season_6.setText("")
        self.image_7.setText("")
        self.player_name_7.setText("")
        self.season_7.setText("")
        self.image_8.setText("")
        self.player_name_8.setText("")
        self.season_8.setText("")
        self.image_9.setText("")
        self.player_name_9.setText("")
        self.season_9.setText("")
        self.image_10.setText("")
        self.player_name_10.setText("")
        self.season_10.setText("")
        self.image_11.setText("")
        self.player_name_11.setText("")
        self.season_11.setText("")
        self.image_12.setText("")
        self.player_name_12.setText("")
        self.season_12.setText("")
        self.trio1_name_input.setText(QCoreApplication.translate("MainWindow", u"1e trio", None))
        self.trio2_name_input.setText(QCoreApplication.translate("MainWindow", u"2e trio", None))
        self.trio3_name_input.setText(QCoreApplication.translate("MainWindow", u"3e trio", None))
        self.trio4_name_input.setText(QCoreApplication.translate("MainWindow", u"4e trio", None))
        self.tabs_object.setTabText(self.tabs_object.indexOf(self.at_tab), QCoreApplication.translate("MainWindow", u"\u2694\ufe0f Attacking Trios", None))
        self.image_13.setText("")
        self.player_name_13.setText("")
        self.season_13.setText("")
        self.image_14.setText("")
        self.player_name_14.setText("")
        self.season_16.setText("")
        self.trio1_name_input_2.setText(QCoreApplication.translate("MainWindow", u"1e pair", None))
        self.image_16.setText("")
        self.player_name_15.setText("")
        self.season_14.setText("")
        self.trio1_name_input_3.setText(QCoreApplication.translate("MainWindow", u"2e pair", None))
        self.image_17.setText("")
        self.player_name_16.setText("")
        self.season_17.setText("")
        self.image_19.setText("")
        self.player_name_17.setText("")
        self.season_15.setText("")
        self.trio1_name_input_4.setText(QCoreApplication.translate("MainWindow", u"3e pair", None))
        self.image_20.setText("")
        self.player_name_18.setText("")
        self.season_18.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Starter Goalkeeper", None))
        self.image_18.setText("")
        self.player_name_20.setText("")
        self.season_20.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Backup Goalkeeper", None))
        self.image_15.setText("")
        self.player_name_19.setText("")
        self.season_19.setText("")
        self.tabs_object.setTabText(self.tabs_object.indexOf(self.dp_tab), QCoreApplication.translate("MainWindow", u"\U0001f6e1\U0000fe0f Defenders Pairs", None))
        self.image_21.setText("")
        self.player_name_21.setText("")
        self.season_21.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"LW", None))
        self.image_22.setText("")
        self.player_name_22.setText("")
        self.season_22.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"RW", None))
        self.image_23.setText("")
        self.player_name_23.setText("")
        self.season_23.setText("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.image_24.setText("")
        self.player_name_24.setText("")
        self.season_24.setText("")
        self.image_25.setText("")
        self.player_name_25.setText("")
        self.season_25.setText("")
        self.image_26.setText("")
        self.player_name_26.setText("")
        self.season_26.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"LD", None))
        self.image_27.setText("")
        self.player_name_27.setText("")
        self.season_27.setText("")
        self.image_28.setText("")
        self.player_name_28.setText("")
        self.season_28.setText("")
        self.image_29.setText("")
        self.player_name_29.setText("")
        self.season_29.setText("")
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"RD", None))
        self.image_30.setText("")
        self.player_name_30.setText("")
        self.season_30.setText("")
        self.image_31.setText("")
        self.player_name_31.setText("")
        self.season_31.setText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.image_32.setText("")
        self.player_name_32.setText("")
        self.season_32.setText("")
        self.tabs_object.setTabText(self.tabs_object.indexOf(self.r_tab), QCoreApplication.translate("MainWindow", u"\U0001f4bc Reserve", None))
        self.chat_widget.setPlainText(QCoreApplication.translate("MainWindow", u"(\U0001f9d1\U0000200d\U0001f4bb Draft Logger): To begin, I'll need the name of the player you'd like, please. \U0001f642", None))
        self.tabs_object.setTabText(self.tabs_object.indexOf(self.ap_tab), QCoreApplication.translate("MainWindow", u"\U0001f9cd Add Player", None))
        self.tabs_object.setTabText(self.tabs_object.indexOf(self.s_tab), QCoreApplication.translate("MainWindow", u"\U0001f50e Search", None))
        self.menu_functions.setTitle(QCoreApplication.translate("MainWindow", u"Functions", None))
    # retranslateUi

